### ISSUE TITLE
First Wonder - Pyramid of Giza: Level 1

### ISSUE THREAD

**Issue by Martinio91** [Martinio91/GitHub_GameJam#1]
This will be an epic ticket that will primarily focus on these aspects:

- [x] Simple puzzles (e.g. moving box into a place) #2
- [x]  Collectables #3 
- [x] Level design #4 
- [x] Drawing of a setting (Basic Unity object is okay for now)
- [ ] Goal is a key that leads to uncovering the Library of A
- [x] UI for gameplay (Collecting item) #5 

Additional Inclusions (But not required)
- Booby traps
